### ISSUE TITLE
Bluetooth permission problems with old Android devices 

### ISSUE THREAD

**Issue by SonjaNueAmperias** [YoussefHenna/expo-enode-link-sdk#13]
Hey, I have issues with older Android devices. I am currently testing on two devices:

- Huawei Smartphone: Android 6, API level 23
- Lenovo Tablet: Android 10, API level 29

This expo module works fine with new Android devices and all iOS devices, but with the two devices I listed above, I have problems with the bluetooth permissions. I believe that the problem comes from the fact that new permission handling for bluetooth was introduced with Android API level 31.

### How the error happens:

**Android 6**
I open the app and get the URL to link the electric car from our BE. When I try to open the URL with `ExpoEnodeLinkSDK.show(...)` the app first requests the permission for the location and afterwards crashes. The terminal prints the following error: 
```
Your app just crashed. See the error below.
java.lang.RuntimeException: Unable to resume activity {com.eon.home.eu/com.eon.home.eu.MainActivity}: java.lang.reflect.InvocationTargetException
  android.app.ActivityThread.performResumeActivity(ActivityThread.java:3154)
  android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3185)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
  android.os.Handler.dispatchMessage(Handler.java:102)
  android.os.Looper.loop(Looper.java:150)
  android.app.ActivityThread.main(ActivityThread.java:5643)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
Caused by java.lang.reflect.InvocationTargetException
  java.lang.reflect.Method.invoke(Native Method)
  expo.modules.ReactActivityDelegateWrapper.invokeDelegateMethod(ReactActivityDelegateWrapper.kt:285)
  expo.modules.ReactActivityDelegateWrapper.onResume(ReactActivityDelegateWrapper.kt:163)
  com.facebook.react.ReactActivity.onResume(ReactActivity.java:58)
  android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
  android.app.Activity.performResume(Activity.java:6451)
  android.app.ActivityThread.performResumeActivity(ActivityThread.java:3144)
  android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3185)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
  android.os.Handler.dispatchMessage(Handler.java:102)
  android.os.Looper.loop(Looper.java:150)
  android.app.ActivityThread.main(ActivityThread.java:5643)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
Caused by java.lang.IllegalArgumentException: Unknown permission: android.permission.BLUETOOTH_SCAN
  android.os.Parcel.readException(Parcel.java:1606)
  android.os.Parcel.readException(Parcel.java:1555)
  android.content.pm.IPackageManager$Stub$Proxy.shouldShowRequestPermissionRationale(IPackageManager.java:2699)
  android.app.ApplicationPackageManager.shouldShowRequestPermissionRationale(ApplicationPackageManager.java:539)
  android.app.Activity.shouldShowRequestPermissionRationale(Activity.java:3970)
  androidx.core.app.ActivityCompat$Api23Impl.shouldShowRequestPermissionRationale(ActivityCompat.java:943)
  androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:601)
  expo.modules.adapters.react.permissions.PermissionsService.canAskAgain(PermissionsService.kt:201)
  expo.modules.adapters.react.permissions.PermissionsService.getPermissionResponseFromNativeResponse(PermissionsService.kt:222)
  expo.modules.adapters.react.permissions.PermissionsService.parseNativeResult(PermissionsService.kt:208)
  expo.modules.adapters.react.permissions.PermissionsService.createListenerWithPendingPermissionsRequest$lambda$22(PermissionsService.kt:271)
  expo.modules.adapters.react.permissions.PermissionsService.$r8$lambda$hmbyKVSQEVIO5W4sPAkDecGzoKE(PermissionsService.kt)
  expo.modules.adapters.react.permissions.PermissionsService$$ExternalSyntheticLambda0.onRequestPermissionsResult(D8$$SyntheticClass)
  com.facebook.react.ReactActivityDelegate$2.invoke(ReactActivityDelegate.java:201)
  com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:126)
  java.lang.reflect.Method.invoke(Native Method)
  expo.modules.ReactActivityDelegateWrapper.invokeDelegateMethod(ReactActivityDelegateWrapper.kt:285)
  expo.modules.ReactActivityDelegateWrapper.onResume(ReactActivityDelegateWrapper.kt:163)
  com.facebook.react.ReactActivity.onResume(ReactActivity.java:58)
  android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
  android.app.Activity.performResume(Activity.java:6451)
  android.app.ActivityThread.performResumeActivity(ActivityThread.java:3144)
  android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3185)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
  android.os.Handler.dispatchMessage(Handler.java:102)
  android.os.Looper.loop(Looper.java:150)
  android.app.ActivityThread.main(ActivityThread.java:5643)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
```

**Android 10**
I open the app and get the URL to link the electric car from our BE. When I try to open the URL with `ExpoEnodeLinkSDK.show(...)` the app first requests the permission for the location and afterwards doesn't show the link UI flow, but I get the following code and errorMessage in the result listener `ExpoEnodeLinkSDK.listenToResult((code, errorMessage) => {...}` .
```
code:  permissionError
errorMessage:  One or more of the required permissions are missing or not granted (ACCESS_FINE_LOCATION, BLUETOOTH_SCAN, BLUETOOTH_CONNECT)
```
For this device / Android version the app doesn't crash. 

### Other observations
Differences I noticed for newer and older Android versions:
When I go to app permissions in the system preferences for newer devices I see "Nearby devices" listed as permission. For older devices this permission does not appear (see screenshots)
#### Device with Android API level 33
<img width="329" alt="device_api_33" src="https://github.com/YoussefHenna/expo-enode-link-sdk/assets/82810034/488d8359-47ed-47e3-a304-5bdb2f3affd0">

#### Device with Android API level 23
<img width="329" alt="device_api_33" src="https://github.com/YoussefHenna/expo-enode-link-sdk/assets/82810034/8b672114-c31e-40f7-8e3e-2fa9d6a75497">
<br/><br/>

Any ideas? I've been stuck with this for a week. I tried to add the permissions to _app.json_ and _app.config.ts_ and also tried to request the permission with `PermissionsAndroid.request(...)` before the linking process, but I couldn't get it to work.
<br/><br/>

Does anyone have the same problems?
It would be great if someone could help me. Thank you very much :)

**Comment by YoussefHenna** [comment]
Hey, thanks for the detailed bug report! I admit that I did not properly test this out on older devices. I'm sure permissions need to be handled differently in that case, I'll look into it and try to address the issue soon.

**Comment by YoussefHenna** [comment]
@SonjaNueAmperias I just released `v0.4.3`. Please try that out and let me know if that works.

**Comment by SonjaNueAmperias** [comment]
@YoussefHenna, thank you so much for your fast response and the fast solution. For the Android 10 device the new version is working perfectly fine 🎉. 

Unfortunately, it still does not work on the Android 6 device. However, the behavior has changed. The app no longer crashes. Instead, the In-App-Browser opens showing a blanc screen (see screenshot). When I copy the URL from the In-App-Browser and paste it into the chrome app, I can go through the linking flow. Then after I get redirected to the app I get the following errorMessage and code.
```
code: unknownError
errorMessage: null
```

<img src="https://github.com/YoussefHenna/expo-enode-link-sdk/assets/82810034/a173ae93-02ba-4a1b-8e5b-d6248741917b" alt="Android 6 device showing blanc In-App-Browser" width="329"/>

Do you have any idea where the problem is coming from? As the error only occurs on the very old device, I don't know how important it is to investigate this error any further.
I will test other old Android versions with the help of the emulator and will let you know if I notice anything.

Thank you so much for you help!

**Comment by YoussefHenna** [comment]
Hmm. This package only launches the Enode link SDK, so this issue might be an underlying issue with the Enode SDK itself rather than something going on with this expo implementation of it. It's possible that it does not support older android versions, I'd say you can contact them through here: https://developers.enode.com/support, they're a supportive team and tend to help out when asked. 

Testing out other devices is also a good idea, please let me know how that goes!
